#!/usr/bin/env bash

function print_help(){
    echo "Clara Bootstrap v1.0"
    echo -e "\tusage: clara scaffold <java|python> <PROJECT_NAME>"
    echo -e "\tusage: clara install <python> [CUSTOM_CLARA_REPOSITORY] [CUSTOM_CLARA_INSTALL_DIRECTORY]"
}

if [ -z "$1" ]; then
    print_help
    exit 0
fi

if [ "$1" = "-h" -o "$1" = "-help" ]; then
    print_help
    exit 0
fi

option=$1

if [ "$option" = "scaffold" ]; then
    language=$2
    proj_name=$3
    if [ "$language" = "python" ]; then
        python -c "from clara_bootstrap.generator.PythonProject import create_python_project; create_python_project(\"$proj_name\")"
    elif [ "$language" = "java" ]; then
        python -c "from clara_bootstrap.generator.JavaProject import create_java_project; create_java_project(\"$proj_name\")"
    else
        print_help
    fi
elif [ "$option" = "install" ]; then
    language=$2
    if [ "$language" = "python" ]; then
        repo=$3
        install_dir=$4
        if [[ -n $repo ]]; then
            if [ -n install_dir ]; then
                python -c "from clara_bootstrap.installer.PythonInstaller import install; install(\"$repo\", \"$install_dir\")"
            else
                python -c "from clara_bootstrap.installer.PythonInstaller import install; install(\"$repo\")"
            fi
        else
            echo "No argumentss...."
            python -c "from clara_bootstrap.installer.PythonInstaller import install; install()"
        fi

    else
        echo "Not supported language for bootstrap setup..."
    fi
else
    print_help
fi
